name: Continuous Integration and Deployment

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Dependencies
      run: npm install

    - name: Install ESLint
      run: npm install eslint

    - name: Run ESLint
      run: npx eslint 
      
    - name: Run Tests
      run: npm test

    - name: Code Coverage
      run: npm run test:coverage

    - name: Deploy to Test Environment
      if: github.event_name == 'push' && github.ref == 'refs/heads/development'
      run: |
        npm install
        npm run build
        npm start

  deploy_prod:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Deploy to Production
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
          npm install
          npm run build

  monitor_prod:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Monitor Production Environment
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        chmod +x monitoring_script.sh
        ./monitoring_script.sh
